blank_issues_enabled: false
contact_links:
  - name: Slack Community Chat
    url: https://livekit.io/join-slack
    about: Ask questions and discuss with other LiveKit users in real time.
  - name: My Discord
    url: https://discord.gg/v6nj7dShND
    about: Ask questions and discuss with me. Lets build.